### ISSUE TITLE
Problème date

### ISSUE THREAD

**Issue by vvnsrzn** [Tchangang/covid-attestation#1]
Tout d'abord merci pour cette appli !
Par contre, je vois une petite erreur sur la génération du pdf: ![image](https://user-images.githubusercontent.com/9358572/97959979-c7e42780-1db0-11eb-9f3b-ebcff66b24cb.png)

Normalement ça devrait être 03/11/2020 :thinking:

**Comment by Tchangang** [comment]
Je corrige ça de suite 👍 Merci Vivian
